/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2020-07-31 11:00:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class edit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\" integrity=\"sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk\" crossorigin=\"anonymous\">\r\n");
      out.write("    <title>Insert Employee</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarTogglerDemo01\" aria-controls=\"navbarTogglerDemo01\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarTogglerDemo01\">\r\n");
      out.write("    <ul class=\"navbar-nav mr-auto mt-2 mt-lg-0\">\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"index.jsp\">Home <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"insert.jsp\">เพิ่มประวัติ</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <form class=\"form-inline my-2 my-lg-0\" name=\"frmSearch\" method=\"post\" action=\"search.jsp\">\r\n");
      out.write("      <input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\" id=\"Keyword\" name=\"Keyword\">\r\n");
      out.write("      <button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      ");
 
                Connection connect = null;
            	ResultSet rec = null;
            	Statement s= null;
	try {
		Class.forName("com.mysql.jdbc.Driver");
		connect =  DriverManager.getConnection("jdbc:mysql://localhost/employee" +
				"?user=root&password=");
		s = connect.createStatement();
		String sql="SELECT * FROM employee emp LEFT JOIN department de ON de.Department_ID = emp.Department_ID WHERE emp.ID = '"+request.getParameter("ID")+"'";
		rec=s.executeQuery(sql);

		
	} catch (Exception e) {
		// TODO Auto-generated catch block
		out.println(e.getMessage());
		e.printStackTrace();
	}
	
	
      out.write('\r');
      out.write('\n');
      out.write('	');
 while((rec!=null)&&(rec.next())) {
      out.write("\r\n");
      out.write("        <form action=\"edit_data.jsp?ID=");
      out.print( rec.getString("ID") );
      out.write("\" method=\"post\">\r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("                <div class=\"form-group col-md-2\">\r\n");
      out.write("                    <label for=\"inputName_Prefix\">คำนำหน้า</label>\r\n");
      out.write("                    <select id=\"Name_Prefix\" class=\"form-control\" name=\"Name_Prefix\">\r\n");
      out.write("                        <option value=\"");
      out.print( rec.getString("Name_Prefix") );
      out.write('"');
      out.write('>');
      out.print( rec.getString("Name_Prefix") );
      out.write("</option>\r\n");
      out.write("                        <option value=\"นาย\">นาย</option>\r\n");
      out.write("                        <option value=\"นาง\">นาง</option>\r\n");
      out.write("                        <option value=\"นางสาว\">นางสาว</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group col-md-5\">\r\n");
      out.write("                    <label for=\"inputFirst_Name\">ชื่อ</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"First_Name\" name=\"First_Name\" value=\"");
      out.print( rec.getString("First_Name") );
      out.write("\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group col-md-5\">\r\n");
      out.write("                    <label for=\"inputLast_Name\">นามสกุล</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"Last_Name\" name=\"Last_Name\" value=\"");
      out.print( rec.getString("Last_Name") );
      out.write("\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("                <div class=\"form-group col-md-5\">\r\n");
      out.write("                    <label for=\"inputFirst_Name_Eng\">First Name</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"First_Name_Eng\" name=\"First_Name_Eng\" value=\"");
      out.print( rec.getString("First_Name_Eng") );
      out.write("\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group col-md-5\">\r\n");
      out.write("                    <label for=\"inputLast_Name_Eng\">Last Name</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"Last_Name_Eng\" name=\"Last_Name_Eng\" value=\"");
      out.print( rec.getString("Last_Name_Eng") );
      out.write("\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group col-md-2\">\r\n");
      out.write("                    <label for=\"inputSex\">เพศ</label>\r\n");
      out.write("                    <select id=\"Sex\" class=\"form-control\" name=\"Sex\">\r\n");
      out.write("                        <option value=\"");
      out.print( rec.getString("Sex") );
      out.write('"');
      out.write('>');
      out.print( rec.getString("Sex") );
      out.write("</option>\r\n");
      out.write("                        <option value=\"ชาย\">ชาย</option>\r\n");
      out.write("                        <option value=\"หญิง\">หญิง</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("                <div class=\"form-group col-md-3\">\r\n");
      out.write("                    <label for=\"inputBirth_Date\">วันเกิด</label>\r\n");
      out.write("                    <input type=\"date\" class=\"form-control\" id=\"Birth_Date\" name=\"Birth_Date\" value=\"");
      out.print( rec.getString("Birth_Date") );
      out.write("\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group col-md-3\">\r\n");
      out.write("                    <label for=\"inputNationality\">สัญชาติ</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"Nationality\" name=\"Nationality\" value=\"");
      out.print( rec.getString("Nationality") );
      out.write("\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group col-md-3\">\r\n");
      out.write("                    <label for=\"inputRace\">เชื่อชาติ</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"Race\" name=\"Race\" value=\"");
      out.print( rec.getString("Race") );
      out.write("\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group col-md-3\">\r\n");
      out.write("                    <label for=\"inputReligion\">ศาสนา</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"Religion\" name=\"Religion\" value=\"");
      out.print( rec.getString("Religion") );
      out.write("\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("                <div class=\"form-group col-md-3\">\r\n");
      out.write("                    <label for=\"inputPlace_of_Birth\">สถานที่เกิด</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"Place_of_Birth\" name=\"Place_of_Birth\" value=\"");
      out.print( rec.getString("Place_of_Birth") );
      out.write("\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group col-md-3\">\r\n");
      out.write("                    <label for=\"inputAge\">อายุ</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"Age\" name=\"Age\" value=\"");
      out.print( rec.getString("Age") );
      out.write("\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group col-md-3\">\r\n");
      out.write("                    <label for=\"inputWeight\">น้ำหนัก</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"Weight\" name=\"Weight\" value=\"");
      out.print( rec.getString("Weight") );
      out.write("\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group col-md-3\">\r\n");
      out.write("                    <label for=\"inputHeight\">ส่วนสูง</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"Height\" name=\"Height\" value=\"");
      out.print( rec.getString("Height") );
      out.write("\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("                <div class=\"form-group col-md-12\">\r\n");
      out.write("                    <label for=\"inputPresent_Address\">ที่อยู่ปัจจุบัน</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"Present_Address\" name=\"Present_Address\" value=\"");
      out.print( rec.getString("Present_Address") );
      out.write("\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"form-row\">\r\n");
      out.write("            <div class=\"form-group col-md-3\">\r\n");
      out.write("                    <label for=\"inputHome_Tel\">โทรศัพท์บ้าน</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"Home_Tel\" name=\"Home_Tel\" value=\"");
      out.print( rec.getString("Home_Tel") );
      out.write("\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group col-md-3\">\r\n");
      out.write("                    <label for=\"inputMobile\">มือถือ</label>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"Mobile\" name=\"Mobile\" value=\"");
      out.print( rec.getString("Mobile") );
      out.write("\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group col-md-3\">\r\n");
      out.write("                    <label for=\"inputE-mail\">ที่อยู่อีเมล์</label>\r\n");
      out.write("                    <input type=\"email\" class=\"form-control\" id=\"E-mail\" name=\"E-mail\" value=\"");
      out.print( rec.getString("E-mail") );
      out.write("\">\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 
	try {
		Class.forName("com.mysql.jdbc.Driver");
		connect =  DriverManager.getConnection("jdbc:mysql://localhost/employee" +
				"?user=root&password=");
		s = connect.createStatement();
		String sql="SELECT * FROM department";
		rec=s.executeQuery(sql);

		
	} catch (Exception e) {
		// TODO Auto-generated catch block
		out.println(e.getMessage());
		e.printStackTrace();
	}
	
	
      out.write("\r\n");
      out.write("                <div class=\"form-group col-md-3\">\r\n");
      out.write("                    <label for=\"inputDepartment_ID\">แผนก</label>\r\n");
      out.write("                    <select id=\"Department_ID\" class=\"form-control\" name=\"Department_ID\">\r\n");
      out.write("                        ");
 while((rec!=null)&&(rec.next())) {
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print( rec.getString("Department_ID") );
      out.write('"');
      out.write('>');
      out.print( rec.getString("Department_Name") );
      out.write("</option>\r\n");
      out.write("                         ");
 } 
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary\">save</button>\r\n");
      out.write("        </form>\r\n");
      out.write("         ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\" integrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\" integrity=\"sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
